### PR TITLE
Restore last state for power state

### PR DESCRIPTION
**Pull request by michbeck100**
This PR fixes the issue that pimatic-led-light cannot restore the last power state, when pimatic was restarted. To fix this i had to use boolean values for the power state throughout the complete plugin. This was mixed sometimes with strings. Furthermore was the last state not forwarded to the device classes.

### CODE REVIEW

**Comment by michbeck100** [comment]
Oh, and this PR fixes the CI errors with Travis.

**Comment by michbeck100** [comment]
@mwittig Did have the time to review my changes?

**Comment by michbeck100** [comment]
@mwittig I've seen your last commit d5a81d1. This PR does the same but much more. It completely uses boolean values for the state. Furthermore it resolves this annoying bug that every light gets switched on when restarting pimatic using this plugin. It would be great if anyone could review the changes and hopefully merge and release them.

**Comment by mwittig** [comment]
I had issues with that. Did you test your changes with the frontend?

**Comment by michbeck100** [comment]
Yes i did test successfully. Also the frontend. Maybe you have to clear the caches? I will test again, maybe some changes in the mean time broke it.

**Comment by michbeck100** [comment]
@mwittig Can you tell what problems you had?

**Comment by michbeck100** [comment]
I've merged the latest changes from 0.9.x and tested again. I had some issues but these were related to the caching of the frontend. Please try to clear caches and remove any precompiled js files.

**Comment by michbeck100** [comment]
@mwittig will you release a new version of pimatic-led-light so i can finish https://github.com/michbeck100/pimatic-hap/issues/54?

**Comment by mwittig** [comment]
Will do, however, I am travelling right now up to end of next week with limited access to the computer/internet.

**Comment by michbeck100** [comment]
Any updates on this?

**Comment by michbeck100** [comment]
@mwittig back from traveling? 😁 will there be a new release?

**Pull request merged**
